apiVersion: apps/v1
kind: Deployment
metadata:
  name: sad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sad
  template:
    metadata:
      labels:
        app: sad
    spec:
      containers:
      - image: okteto.dev/sad:latest
        name: sad
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "a11f7e18-48ee-4d2c-9441-f8c1b03c8f3d"
        - name: Vless_Path
          value: "/vhdg66Lfd"
        - name: Vmess_UUID
          value: "a11f7e18-48ee-4d2c-9441-f8c1b03c8f3d"
        - name: Vmess_Path
          value: "/vyds69Mjg"
        - name: Share_Path
          value: "$Share_Path"
